language: python

python:
  - 3.6

bundler_args: --retry 3

install:
 # - sudo apt-get install -y r-base
 # - sudo apt-get install -y r-cran-foreign
  - sudo apt-get update
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - conda env create -f environment.yml
  - source activate student_project

script:
   # This automatically executes all notebooks (*.ipynb)
   # in the root directory. If you only want to execute
   # selected notebooks or notebooks in subdirectories,
   # please go ahead and edit the file to meet your 
   # needs..
   - travis_wait python utils/travis_runner.py
